### ISSUE TITLE
chainsaw v0.2.13 does not build on Go 1.26 or newer

### ISSUE THREAD

**Issue by ecv** [milo-os/milo#779]
## What happens

`task generate:test-docs` and `task test:end-to-end` install chainsaw at the version pinned in the Taskfile. On Go 1.26 or newer the install fails:

```
pkg/runner/runner.go:222:25: cannot use deps (variable of type *"github.com/kyverno/chainsaw/pkg/runner/internal".TestDeps) as "testing".testDeps value in argument to testing.MainStart: *".../internal".TestDeps does not implement "testing".testDeps (missing method ModulePath)
```

CI has not hit it because the workflow resolves Go from `go.mod`, which pins 1.25.0. A local machine on a newer Go cannot run either task.

## Fix

Bump the pin to chainsaw v0.2.15, which carries the upstream fix (kyverno/chainsaw#2646). That release declares Go 1.26, so the install then depends on the Go toolchain auto-switch. Make that dependency explicit rather than proxy-dependent.

The generated test READMEs also need a refresh. One of them has been stale since commit `4b438d49` added a script operation without regenerating, and no workflow checks for that drift.

**Comment by ecv** [comment]
Fixed in #777. The chainsaw pin is at v0.2.15 and tracked by Renovate, `go.mod` pins the Go toolchain so the install no longer leans on the auto-switch, and the stale test READMEs were regenerated.

The missing drift check for those READMEs, which is how one of them went stale, is filed separately so it is not lost.

- https://github.com/milo-os/milo/issues/786
